# Generated by Django 4.0 on 2021-12-25 06:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda_de_peça',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrição', models.TextField()),
                ('rua', models.TextField()),
                ('cidade', models.TextField()),
                ('estado', models.TextField()),
                ('cep', models.IntegerField()),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Finalizada', 'Finalizada')], default='Aberta', max_length=20)),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='auth.user')),
            ],
        ),
    ]
